name: Lint

on: [push]

jobs:
  lint:
    strategy:
      matrix:
        target: ['18']
    uses: snapshot-labs/actions/.github/workflows/lint.yml@main
    with:
      target: ${{ matrix.target }}
    secrets: inherit
